eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
    password: ${USER_PASSWORD:password}
security:
  user:
    password: ${eureka.password}

spring:
  application:
    name: product-shop-images
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
